name: Fiyat Guncelle
on:
  schedule:
    - cron: '*/5 * * * *' # Her 5 dakikada bir çalışır
  workflow_dispatch: # Manuel çalıştırma butonu ekler

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - name: Veriyi Cek ve Firebase'e Yaz
        run: |
          # Altın ve Döviz verilerini çek
          GOLD=$(curl -s https://static.altinkaynak.com/public/Gold)
          CURR=$(curl -s https://static.altinkaynak.com/public/Currency)
          
          # Veriyi tek bir paket yap
          DATA="{\"gold\": $GOLD, \"currency\": $CURR}"
          
          # Firebase'e gönder (Senin linkin)
          curl -X PUT -d "$DATA" "https://piyasa-9049c-default-rtdb.firebaseio.com/piyasa.json"
