name: Veri Guncelleme
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Tum Verileri Cek
        run: |
          # Hava Durumu
          curl -s "https://wttr.in/Ankara?format=j1" > hava.json
          # Namaz Vakitleri
          curl -s "https://muslimsalat.com/ankara/daily.json" > namaz.json
          # Haberler (RSS to JSON servisi ile son dakika haberleri)
          curl -s "https://api.rss2json.com/v1/api.json?rss_url=https://www.trthaber.com/manset_articles.rss" > haber.json
          
          # Firebase'e GÃ¶nder
          curl -X PUT -d @hava.json "https://piyasa-9049c-default-rtdb.firebaseio.com/hava.json"
          curl -X PUT -d @namaz.json "https://piyasa-9049c-default-rtdb.firebaseio.com/namaz.json"
          curl -X PUT -d @haber.json "https://piyasa-9049c-default-rtdb.firebaseio.com/haber.json"
